/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.boxalino.p13n.api.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * <dl>
 * <dt>variantId</dt>
 * <dd>id of the personalized variant</dd>
 * 
 * <dt>scenarioId</dt>
 * <dd>scenario identificator used to produce recommendation result or search
 * result personalization</dd>
 * 
 * <dt>searchResult</dt>
 * <dd>result of the search request for recommendations and search requests</dd>
 * 
 * <dt>searchResultTitle</dt>
 * <dd>recommendation's result title localized in language requested in
 * corresponding SimpleSearchQuery</dd>
 * 
 * <dt>searchRelaxation</dt>
 * <dd>When the service considers queryText invalid, it will evaluate and return
 * relaxations if it is requested in corresponding ChoiceInquiry and if
 * relaxations could be found.</dd>
 * <dd>Note that original query still could yield some results; it is up to the
 * client to decide whether searchRelaxations should be used (with displaying
 * appropriate message) or not.</dd>
 * </dl>
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-01-25")
public class Variant implements org.apache.thrift.TBase<Variant, Variant._Fields>, java.io.Serializable, Cloneable, Comparable<Variant> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Variant");

  private static final org.apache.thrift.protocol.TField VARIANT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("variantId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SCENARIO_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("scenarioId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SEARCH_RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("searchResult", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField SEARCH_RESULT_TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("searchResultTitle", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField SEARCH_RELAXATION_FIELD_DESC = new org.apache.thrift.protocol.TField("searchRelaxation", org.apache.thrift.protocol.TType.STRUCT, (short)50);
  private static final org.apache.thrift.protocol.TField SEMANTIC_FILTERING_RESULTS_FIELD_DESC = new org.apache.thrift.protocol.TField("semanticFilteringResults", org.apache.thrift.protocol.TType.LIST, (short)60);
  private static final org.apache.thrift.protocol.TField EXTRA_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("extraInfo", org.apache.thrift.protocol.TType.MAP, (short)70);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new VariantStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new VariantTupleSchemeFactory();

  public java.lang.String variantId; // required
  public java.lang.String scenarioId; // required
  public SearchResult searchResult; // required
  public java.lang.String searchResultTitle; // required
  public SearchRelaxation searchRelaxation; // required
  public java.util.List<SearchResult> semanticFilteringResults; // required
  public java.util.Map<java.lang.String,java.lang.String> extraInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VARIANT_ID((short)1, "variantId"),
    SCENARIO_ID((short)2, "scenarioId"),
    SEARCH_RESULT((short)3, "searchResult"),
    SEARCH_RESULT_TITLE((short)4, "searchResultTitle"),
    SEARCH_RELAXATION((short)50, "searchRelaxation"),
    SEMANTIC_FILTERING_RESULTS((short)60, "semanticFilteringResults"),
    EXTRA_INFO((short)70, "extraInfo");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VARIANT_ID
          return VARIANT_ID;
        case 2: // SCENARIO_ID
          return SCENARIO_ID;
        case 3: // SEARCH_RESULT
          return SEARCH_RESULT;
        case 4: // SEARCH_RESULT_TITLE
          return SEARCH_RESULT_TITLE;
        case 50: // SEARCH_RELAXATION
          return SEARCH_RELAXATION;
        case 60: // SEMANTIC_FILTERING_RESULTS
          return SEMANTIC_FILTERING_RESULTS;
        case 70: // EXTRA_INFO
          return EXTRA_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VARIANT_ID, new org.apache.thrift.meta_data.FieldMetaData("variantId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SCENARIO_ID, new org.apache.thrift.meta_data.FieldMetaData("scenarioId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SEARCH_RESULT, new org.apache.thrift.meta_data.FieldMetaData("searchResult", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchResult.class)));
    tmpMap.put(_Fields.SEARCH_RESULT_TITLE, new org.apache.thrift.meta_data.FieldMetaData("searchResultTitle", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SEARCH_RELAXATION, new org.apache.thrift.meta_data.FieldMetaData("searchRelaxation", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchRelaxation.class)));
    tmpMap.put(_Fields.SEMANTIC_FILTERING_RESULTS, new org.apache.thrift.meta_data.FieldMetaData("semanticFilteringResults", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchResult.class))));
    tmpMap.put(_Fields.EXTRA_INFO, new org.apache.thrift.meta_data.FieldMetaData("extraInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Variant.class, metaDataMap);
  }

  public Variant() {
  }

  public Variant(
    java.lang.String variantId,
    java.lang.String scenarioId,
    SearchResult searchResult,
    java.lang.String searchResultTitle,
    SearchRelaxation searchRelaxation,
    java.util.List<SearchResult> semanticFilteringResults,
    java.util.Map<java.lang.String,java.lang.String> extraInfo)
  {
    this();
    this.variantId = variantId;
    this.scenarioId = scenarioId;
    this.searchResult = searchResult;
    this.searchResultTitle = searchResultTitle;
    this.searchRelaxation = searchRelaxation;
    this.semanticFilteringResults = semanticFilteringResults;
    this.extraInfo = extraInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Variant(Variant other) {
    if (other.isSetVariantId()) {
      this.variantId = other.variantId;
    }
    if (other.isSetScenarioId()) {
      this.scenarioId = other.scenarioId;
    }
    if (other.isSetSearchResult()) {
      this.searchResult = new SearchResult(other.searchResult);
    }
    if (other.isSetSearchResultTitle()) {
      this.searchResultTitle = other.searchResultTitle;
    }
    if (other.isSetSearchRelaxation()) {
      this.searchRelaxation = new SearchRelaxation(other.searchRelaxation);
    }
    if (other.isSetSemanticFilteringResults()) {
      java.util.List<SearchResult> __this__semanticFilteringResults = new java.util.ArrayList<SearchResult>(other.semanticFilteringResults.size());
      for (SearchResult other_element : other.semanticFilteringResults) {
        __this__semanticFilteringResults.add(new SearchResult(other_element));
      }
      this.semanticFilteringResults = __this__semanticFilteringResults;
    }
    if (other.isSetExtraInfo()) {
      java.util.Map<java.lang.String,java.lang.String> __this__extraInfo = new java.util.HashMap<java.lang.String,java.lang.String>(other.extraInfo);
      this.extraInfo = __this__extraInfo;
    }
  }

  public Variant deepCopy() {
    return new Variant(this);
  }

  @Override
  public void clear() {
    this.variantId = null;
    this.scenarioId = null;
    this.searchResult = null;
    this.searchResultTitle = null;
    this.searchRelaxation = null;
    this.semanticFilteringResults = null;
    this.extraInfo = null;
  }

  public java.lang.String getVariantId() {
    return this.variantId;
  }

  public Variant setVariantId(java.lang.String variantId) {
    this.variantId = variantId;
    return this;
  }

  public void unsetVariantId() {
    this.variantId = null;
  }

  /** Returns true if field variantId is set (has been assigned a value) and false otherwise */
  public boolean isSetVariantId() {
    return this.variantId != null;
  }

  public void setVariantIdIsSet(boolean value) {
    if (!value) {
      this.variantId = null;
    }
  }

  public java.lang.String getScenarioId() {
    return this.scenarioId;
  }

  public Variant setScenarioId(java.lang.String scenarioId) {
    this.scenarioId = scenarioId;
    return this;
  }

  public void unsetScenarioId() {
    this.scenarioId = null;
  }

  /** Returns true if field scenarioId is set (has been assigned a value) and false otherwise */
  public boolean isSetScenarioId() {
    return this.scenarioId != null;
  }

  public void setScenarioIdIsSet(boolean value) {
    if (!value) {
      this.scenarioId = null;
    }
  }

  public SearchResult getSearchResult() {
    return this.searchResult;
  }

  public Variant setSearchResult(SearchResult searchResult) {
    this.searchResult = searchResult;
    return this;
  }

  public void unsetSearchResult() {
    this.searchResult = null;
  }

  /** Returns true if field searchResult is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchResult() {
    return this.searchResult != null;
  }

  public void setSearchResultIsSet(boolean value) {
    if (!value) {
      this.searchResult = null;
    }
  }

  public java.lang.String getSearchResultTitle() {
    return this.searchResultTitle;
  }

  public Variant setSearchResultTitle(java.lang.String searchResultTitle) {
    this.searchResultTitle = searchResultTitle;
    return this;
  }

  public void unsetSearchResultTitle() {
    this.searchResultTitle = null;
  }

  /** Returns true if field searchResultTitle is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchResultTitle() {
    return this.searchResultTitle != null;
  }

  public void setSearchResultTitleIsSet(boolean value) {
    if (!value) {
      this.searchResultTitle = null;
    }
  }

  public SearchRelaxation getSearchRelaxation() {
    return this.searchRelaxation;
  }

  public Variant setSearchRelaxation(SearchRelaxation searchRelaxation) {
    this.searchRelaxation = searchRelaxation;
    return this;
  }

  public void unsetSearchRelaxation() {
    this.searchRelaxation = null;
  }

  /** Returns true if field searchRelaxation is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchRelaxation() {
    return this.searchRelaxation != null;
  }

  public void setSearchRelaxationIsSet(boolean value) {
    if (!value) {
      this.searchRelaxation = null;
    }
  }

  public int getSemanticFilteringResultsSize() {
    return (this.semanticFilteringResults == null) ? 0 : this.semanticFilteringResults.size();
  }

  public java.util.Iterator<SearchResult> getSemanticFilteringResultsIterator() {
    return (this.semanticFilteringResults == null) ? null : this.semanticFilteringResults.iterator();
  }

  public void addToSemanticFilteringResults(SearchResult elem) {
    if (this.semanticFilteringResults == null) {
      this.semanticFilteringResults = new java.util.ArrayList<SearchResult>();
    }
    this.semanticFilteringResults.add(elem);
  }

  public java.util.List<SearchResult> getSemanticFilteringResults() {
    return this.semanticFilteringResults;
  }

  public Variant setSemanticFilteringResults(java.util.List<SearchResult> semanticFilteringResults) {
    this.semanticFilteringResults = semanticFilteringResults;
    return this;
  }

  public void unsetSemanticFilteringResults() {
    this.semanticFilteringResults = null;
  }

  /** Returns true if field semanticFilteringResults is set (has been assigned a value) and false otherwise */
  public boolean isSetSemanticFilteringResults() {
    return this.semanticFilteringResults != null;
  }

  public void setSemanticFilteringResultsIsSet(boolean value) {
    if (!value) {
      this.semanticFilteringResults = null;
    }
  }

  public int getExtraInfoSize() {
    return (this.extraInfo == null) ? 0 : this.extraInfo.size();
  }

  public void putToExtraInfo(java.lang.String key, java.lang.String val) {
    if (this.extraInfo == null) {
      this.extraInfo = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.extraInfo.put(key, val);
  }

  public java.util.Map<java.lang.String,java.lang.String> getExtraInfo() {
    return this.extraInfo;
  }

  public Variant setExtraInfo(java.util.Map<java.lang.String,java.lang.String> extraInfo) {
    this.extraInfo = extraInfo;
    return this;
  }

  public void unsetExtraInfo() {
    this.extraInfo = null;
  }

  /** Returns true if field extraInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetExtraInfo() {
    return this.extraInfo != null;
  }

  public void setExtraInfoIsSet(boolean value) {
    if (!value) {
      this.extraInfo = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case VARIANT_ID:
      if (value == null) {
        unsetVariantId();
      } else {
        setVariantId((java.lang.String)value);
      }
      break;

    case SCENARIO_ID:
      if (value == null) {
        unsetScenarioId();
      } else {
        setScenarioId((java.lang.String)value);
      }
      break;

    case SEARCH_RESULT:
      if (value == null) {
        unsetSearchResult();
      } else {
        setSearchResult((SearchResult)value);
      }
      break;

    case SEARCH_RESULT_TITLE:
      if (value == null) {
        unsetSearchResultTitle();
      } else {
        setSearchResultTitle((java.lang.String)value);
      }
      break;

    case SEARCH_RELAXATION:
      if (value == null) {
        unsetSearchRelaxation();
      } else {
        setSearchRelaxation((SearchRelaxation)value);
      }
      break;

    case SEMANTIC_FILTERING_RESULTS:
      if (value == null) {
        unsetSemanticFilteringResults();
      } else {
        setSemanticFilteringResults((java.util.List<SearchResult>)value);
      }
      break;

    case EXTRA_INFO:
      if (value == null) {
        unsetExtraInfo();
      } else {
        setExtraInfo((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VARIANT_ID:
      return getVariantId();

    case SCENARIO_ID:
      return getScenarioId();

    case SEARCH_RESULT:
      return getSearchResult();

    case SEARCH_RESULT_TITLE:
      return getSearchResultTitle();

    case SEARCH_RELAXATION:
      return getSearchRelaxation();

    case SEMANTIC_FILTERING_RESULTS:
      return getSemanticFilteringResults();

    case EXTRA_INFO:
      return getExtraInfo();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VARIANT_ID:
      return isSetVariantId();
    case SCENARIO_ID:
      return isSetScenarioId();
    case SEARCH_RESULT:
      return isSetSearchResult();
    case SEARCH_RESULT_TITLE:
      return isSetSearchResultTitle();
    case SEARCH_RELAXATION:
      return isSetSearchRelaxation();
    case SEMANTIC_FILTERING_RESULTS:
      return isSetSemanticFilteringResults();
    case EXTRA_INFO:
      return isSetExtraInfo();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Variant)
      return this.equals((Variant)that);
    return false;
  }

  public boolean equals(Variant that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_variantId = true && this.isSetVariantId();
    boolean that_present_variantId = true && that.isSetVariantId();
    if (this_present_variantId || that_present_variantId) {
      if (!(this_present_variantId && that_present_variantId))
        return false;
      if (!this.variantId.equals(that.variantId))
        return false;
    }

    boolean this_present_scenarioId = true && this.isSetScenarioId();
    boolean that_present_scenarioId = true && that.isSetScenarioId();
    if (this_present_scenarioId || that_present_scenarioId) {
      if (!(this_present_scenarioId && that_present_scenarioId))
        return false;
      if (!this.scenarioId.equals(that.scenarioId))
        return false;
    }

    boolean this_present_searchResult = true && this.isSetSearchResult();
    boolean that_present_searchResult = true && that.isSetSearchResult();
    if (this_present_searchResult || that_present_searchResult) {
      if (!(this_present_searchResult && that_present_searchResult))
        return false;
      if (!this.searchResult.equals(that.searchResult))
        return false;
    }

    boolean this_present_searchResultTitle = true && this.isSetSearchResultTitle();
    boolean that_present_searchResultTitle = true && that.isSetSearchResultTitle();
    if (this_present_searchResultTitle || that_present_searchResultTitle) {
      if (!(this_present_searchResultTitle && that_present_searchResultTitle))
        return false;
      if (!this.searchResultTitle.equals(that.searchResultTitle))
        return false;
    }

    boolean this_present_searchRelaxation = true && this.isSetSearchRelaxation();
    boolean that_present_searchRelaxation = true && that.isSetSearchRelaxation();
    if (this_present_searchRelaxation || that_present_searchRelaxation) {
      if (!(this_present_searchRelaxation && that_present_searchRelaxation))
        return false;
      if (!this.searchRelaxation.equals(that.searchRelaxation))
        return false;
    }

    boolean this_present_semanticFilteringResults = true && this.isSetSemanticFilteringResults();
    boolean that_present_semanticFilteringResults = true && that.isSetSemanticFilteringResults();
    if (this_present_semanticFilteringResults || that_present_semanticFilteringResults) {
      if (!(this_present_semanticFilteringResults && that_present_semanticFilteringResults))
        return false;
      if (!this.semanticFilteringResults.equals(that.semanticFilteringResults))
        return false;
    }

    boolean this_present_extraInfo = true && this.isSetExtraInfo();
    boolean that_present_extraInfo = true && that.isSetExtraInfo();
    if (this_present_extraInfo || that_present_extraInfo) {
      if (!(this_present_extraInfo && that_present_extraInfo))
        return false;
      if (!this.extraInfo.equals(that.extraInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetVariantId()) ? 131071 : 524287);
    if (isSetVariantId())
      hashCode = hashCode * 8191 + variantId.hashCode();

    hashCode = hashCode * 8191 + ((isSetScenarioId()) ? 131071 : 524287);
    if (isSetScenarioId())
      hashCode = hashCode * 8191 + scenarioId.hashCode();

    hashCode = hashCode * 8191 + ((isSetSearchResult()) ? 131071 : 524287);
    if (isSetSearchResult())
      hashCode = hashCode * 8191 + searchResult.hashCode();

    hashCode = hashCode * 8191 + ((isSetSearchResultTitle()) ? 131071 : 524287);
    if (isSetSearchResultTitle())
      hashCode = hashCode * 8191 + searchResultTitle.hashCode();

    hashCode = hashCode * 8191 + ((isSetSearchRelaxation()) ? 131071 : 524287);
    if (isSetSearchRelaxation())
      hashCode = hashCode * 8191 + searchRelaxation.hashCode();

    hashCode = hashCode * 8191 + ((isSetSemanticFilteringResults()) ? 131071 : 524287);
    if (isSetSemanticFilteringResults())
      hashCode = hashCode * 8191 + semanticFilteringResults.hashCode();

    hashCode = hashCode * 8191 + ((isSetExtraInfo()) ? 131071 : 524287);
    if (isSetExtraInfo())
      hashCode = hashCode * 8191 + extraInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Variant other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetVariantId()).compareTo(other.isSetVariantId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVariantId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.variantId, other.variantId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetScenarioId()).compareTo(other.isSetScenarioId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScenarioId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scenarioId, other.scenarioId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSearchResult()).compareTo(other.isSetSearchResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchResult, other.searchResult);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSearchResultTitle()).compareTo(other.isSetSearchResultTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchResultTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchResultTitle, other.searchResultTitle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSearchRelaxation()).compareTo(other.isSetSearchRelaxation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchRelaxation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchRelaxation, other.searchRelaxation);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSemanticFilteringResults()).compareTo(other.isSetSemanticFilteringResults());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSemanticFilteringResults()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.semanticFilteringResults, other.semanticFilteringResults);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetExtraInfo()).compareTo(other.isSetExtraInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExtraInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.extraInfo, other.extraInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Variant(");
    boolean first = true;

    sb.append("variantId:");
    if (this.variantId == null) {
      sb.append("null");
    } else {
      sb.append(this.variantId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("scenarioId:");
    if (this.scenarioId == null) {
      sb.append("null");
    } else {
      sb.append(this.scenarioId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("searchResult:");
    if (this.searchResult == null) {
      sb.append("null");
    } else {
      sb.append(this.searchResult);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("searchResultTitle:");
    if (this.searchResultTitle == null) {
      sb.append("null");
    } else {
      sb.append(this.searchResultTitle);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("searchRelaxation:");
    if (this.searchRelaxation == null) {
      sb.append("null");
    } else {
      sb.append(this.searchRelaxation);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("semanticFilteringResults:");
    if (this.semanticFilteringResults == null) {
      sb.append("null");
    } else {
      sb.append(this.semanticFilteringResults);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("extraInfo:");
    if (this.extraInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.extraInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (searchResult != null) {
      searchResult.validate();
    }
    if (searchRelaxation != null) {
      searchRelaxation.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VariantStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public VariantStandardScheme getScheme() {
      return new VariantStandardScheme();
    }
  }

  private static class VariantStandardScheme extends org.apache.thrift.scheme.StandardScheme<Variant> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Variant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VARIANT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.variantId = iprot.readString();
              struct.setVariantIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SCENARIO_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.scenarioId = iprot.readString();
              struct.setScenarioIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SEARCH_RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.searchResult = new SearchResult();
              struct.searchResult.read(iprot);
              struct.setSearchResultIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SEARCH_RESULT_TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.searchResultTitle = iprot.readString();
              struct.setSearchResultTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 50: // SEARCH_RELAXATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.searchRelaxation = new SearchRelaxation();
              struct.searchRelaxation.read(iprot);
              struct.setSearchRelaxationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 60: // SEMANTIC_FILTERING_RESULTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list208 = iprot.readListBegin();
                struct.semanticFilteringResults = new java.util.ArrayList<SearchResult>(_list208.size);
                SearchResult _elem209;
                for (int _i210 = 0; _i210 < _list208.size; ++_i210)
                {
                  _elem209 = new SearchResult();
                  _elem209.read(iprot);
                  struct.semanticFilteringResults.add(_elem209);
                }
                iprot.readListEnd();
              }
              struct.setSemanticFilteringResultsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 70: // EXTRA_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map211 = iprot.readMapBegin();
                struct.extraInfo = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map211.size);
                java.lang.String _key212;
                java.lang.String _val213;
                for (int _i214 = 0; _i214 < _map211.size; ++_i214)
                {
                  _key212 = iprot.readString();
                  _val213 = iprot.readString();
                  struct.extraInfo.put(_key212, _val213);
                }
                iprot.readMapEnd();
              }
              struct.setExtraInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Variant struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.variantId != null) {
        oprot.writeFieldBegin(VARIANT_ID_FIELD_DESC);
        oprot.writeString(struct.variantId);
        oprot.writeFieldEnd();
      }
      if (struct.scenarioId != null) {
        oprot.writeFieldBegin(SCENARIO_ID_FIELD_DESC);
        oprot.writeString(struct.scenarioId);
        oprot.writeFieldEnd();
      }
      if (struct.searchResult != null) {
        oprot.writeFieldBegin(SEARCH_RESULT_FIELD_DESC);
        struct.searchResult.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.searchResultTitle != null) {
        oprot.writeFieldBegin(SEARCH_RESULT_TITLE_FIELD_DESC);
        oprot.writeString(struct.searchResultTitle);
        oprot.writeFieldEnd();
      }
      if (struct.searchRelaxation != null) {
        oprot.writeFieldBegin(SEARCH_RELAXATION_FIELD_DESC);
        struct.searchRelaxation.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.semanticFilteringResults != null) {
        oprot.writeFieldBegin(SEMANTIC_FILTERING_RESULTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.semanticFilteringResults.size()));
          for (SearchResult _iter215 : struct.semanticFilteringResults)
          {
            _iter215.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.extraInfo != null) {
        oprot.writeFieldBegin(EXTRA_INFO_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.extraInfo.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter216 : struct.extraInfo.entrySet())
          {
            oprot.writeString(_iter216.getKey());
            oprot.writeString(_iter216.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VariantTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public VariantTupleScheme getScheme() {
      return new VariantTupleScheme();
    }
  }

  private static class VariantTupleScheme extends org.apache.thrift.scheme.TupleScheme<Variant> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Variant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetVariantId()) {
        optionals.set(0);
      }
      if (struct.isSetScenarioId()) {
        optionals.set(1);
      }
      if (struct.isSetSearchResult()) {
        optionals.set(2);
      }
      if (struct.isSetSearchResultTitle()) {
        optionals.set(3);
      }
      if (struct.isSetSearchRelaxation()) {
        optionals.set(4);
      }
      if (struct.isSetSemanticFilteringResults()) {
        optionals.set(5);
      }
      if (struct.isSetExtraInfo()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetVariantId()) {
        oprot.writeString(struct.variantId);
      }
      if (struct.isSetScenarioId()) {
        oprot.writeString(struct.scenarioId);
      }
      if (struct.isSetSearchResult()) {
        struct.searchResult.write(oprot);
      }
      if (struct.isSetSearchResultTitle()) {
        oprot.writeString(struct.searchResultTitle);
      }
      if (struct.isSetSearchRelaxation()) {
        struct.searchRelaxation.write(oprot);
      }
      if (struct.isSetSemanticFilteringResults()) {
        {
          oprot.writeI32(struct.semanticFilteringResults.size());
          for (SearchResult _iter217 : struct.semanticFilteringResults)
          {
            _iter217.write(oprot);
          }
        }
      }
      if (struct.isSetExtraInfo()) {
        {
          oprot.writeI32(struct.extraInfo.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter218 : struct.extraInfo.entrySet())
          {
            oprot.writeString(_iter218.getKey());
            oprot.writeString(_iter218.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Variant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.variantId = iprot.readString();
        struct.setVariantIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.scenarioId = iprot.readString();
        struct.setScenarioIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.searchResult = new SearchResult();
        struct.searchResult.read(iprot);
        struct.setSearchResultIsSet(true);
      }
      if (incoming.get(3)) {
        struct.searchResultTitle = iprot.readString();
        struct.setSearchResultTitleIsSet(true);
      }
      if (incoming.get(4)) {
        struct.searchRelaxation = new SearchRelaxation();
        struct.searchRelaxation.read(iprot);
        struct.setSearchRelaxationIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list219 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.semanticFilteringResults = new java.util.ArrayList<SearchResult>(_list219.size);
          SearchResult _elem220;
          for (int _i221 = 0; _i221 < _list219.size; ++_i221)
          {
            _elem220 = new SearchResult();
            _elem220.read(iprot);
            struct.semanticFilteringResults.add(_elem220);
          }
        }
        struct.setSemanticFilteringResultsIsSet(true);
      }
      if (incoming.get(6)) {
        {
          org.apache.thrift.protocol.TMap _map222 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.extraInfo = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map222.size);
          java.lang.String _key223;
          java.lang.String _val224;
          for (int _i225 = 0; _i225 < _map222.size; ++_i225)
          {
            _key223 = iprot.readString();
            _val224 = iprot.readString();
            struct.extraInfo.put(_key223, _val224);
          }
        }
        struct.setExtraInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

